name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: 'Features'
    labels:
      - 'feature'
      - 'feat'
  - title: 'Bug Fixes'
    labels:
      - 'fix'
      - 'bug'
  - title: 'Maintenance'
    labels:
      - 'chore'
      - 'ci'
      - 'doc'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
template: |
  ## Changes

  $CHANGES

version-resolver:
  major:
    labels:
      - 'semver:major'
  minor:
    labels:
      - 'semver:minor'
  patch:
    labels:
      - 'semver:patch'
  default: patch
